name: Test Secret

on:
  workflow_dispatch:  # Allows you to manually trigger the workflow

jobs:
  test-secret:
    runs-on: ubuntu-latest

    steps:
    - name: Check if Secret is Set
      run: echo "Secret is available!"
      env:
        TEST_SECRET: ${{ secrets.HEBI-config-nair }}

    - name: Attempt to Use the Secret
      run: |
        if [ -z "$TEST_SECRET" ]; then
          echo "Secret is not set or is invalid"
          exit 1
        else
          echo "Secret is valid: $TEST_SECRET"
        fi
