name: Update Config in Other Repos

on:
  push:
    branches:
      - main

jobs:
  update-config-python:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout robot-config repo
        uses: actions/checkout@v4

      - name: Set up Git
        run: |
          git config --global user.name 'Github Actions robot-config auto-bot'
          git config --global user.email 'developer@hebirobotics.com'

      # --- Python Examples Update Section ---
      - name: Clone hebi-python-examples repo
        env:
          GITHUB_TOKEN: ${{ secrets.OTHER_REPO_PAT }}
        run: |
          git clone https://github.com/HebiRobotics/hebi-python-examples.git
          cd hebi-python-examples
          git config --local credential.helper store
          echo "https://${{ secrets.OTHER_REPO_PAT }}:@github.com" > ~/.git-credentials
          # Delete existing update-config branch if it exists
          git fetch origin
          git branch -D update-config || true
          git push origin --delete update-config || true

      - name: Replace arm's config directory in hebi-python-examples
        run: |
          rm -rf hebi-python-examples/kits/arm/config
          cp -r arms/config hebi-python-examples/kits/arm/config

      - name: Commit and Push changes to hebi-python-examples
        run: |
          cd hebi-python-examples
          git checkout -b update-config
          git add kits/arm/config
          git commit -m "Update config directory from robot-config"
          git push origin update-config

      - name: Create Pull Request for hebi-python-examples
        env:
          GITHUB_TOKEN: ${{ secrets.OTHER_REPO_PAT }}
        run: |
          cd hebi-python-examples
          gh pr create --title "Update config directory from robot-config" --body "This automated PR updates the config directory from the latest version in the robot-config repository." --head update-config --base master

  update-config-cpp:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout robot-config repo
        uses: actions/checkout@v4

      - name: Set up Git
        run: |
          git config --global user.name 'Github Actions robot-config auto-bot'
          git config --global user.email 'developer@hebirobotics.com'

      # --- C++ Examples Update Section ---
      - name: Clone hebi-cpp-examples repo
        env:
          GITHUB_TOKEN: ${{ secrets.OTHER_REPO_PAT }}
        run: |
          git clone https://github.com/HebiRobotics/hebi-cpp-examples.git
          cd hebi-cpp-examples
          git config --local credential.helper store
          echo "https://${{ secrets.OTHER_REPO_PAT }}:@github.com" > ~/.git-credentials
          # Delete existing update-config branch if it exists
          git fetch origin
          git branch -D update-config || true
          git push origin --delete update-config || true

      - name: Replace arm's config directory in hebi-cpp-examples
        run: |
          rm -rf hebi-cpp-examples/kits/arm/config
          cp -r arms/config hebi-cpp-examples/kits/arm/config

      - name: Commit and Push changes to hebi-cpp-examples
        run: |
          cd hebi-cpp-examples
          git checkout -b update-config
          git add kits/arm/config
          git commit -m "Update config directory from robot-config"
          git push origin update-config

      - name: Create Pull Request for hebi-cpp-examples
        env:
          GITHUB_TOKEN: ${{ secrets.OTHER_REPO_PAT }}
        run: |
          cd hebi-cpp-examples
          gh pr create --title "Update config directory from robot-config" --body "This automated PR updates the config directory from the latest version in the robot-config repository." --head update-config --base master
